name: surfacefibrils
channels:
    - conda-forge
    - omnia
    - ambermd
dependencies:
    - python=3
    - numpy
    - scipy
    - pandas
    - matplotlib
    - notebook
    - pytraj=1.0.9
    - openmm=7.0.1
    - pdbfixer=1.3.1
